# -*- mode: ruby -*-
# vi: set ft=ruby :

# Basic vagrant file used for the DisclaimR Vagrant box

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"

  config.vm.network "forwarded_port", guest: 5000, host: 5000
  config.vm.network "forwarded_port", guest: 443, host: 8443
end
